version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
