version: "3.8"

services:
    postgres:
        image: postgres:14
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=wishlists
            - POSTGRES_PASSWORD=secret_pass
            - POSTGRES_DB=wishlists
        volumes:
            - .tmp/postgresql:/var/lib/postgresql
